### ISSUE TITLE
blog.opml is private

### ISSUE THREAD

**Issue by andrewshell** [scripting/myLogseqBlog#2]
Followed the instructions in README.md and when I ran `node mylogseqblog.js` I got the following response (sanitizing tokens):

```
config == {
    "twScreenName": "andrewshell",
    "logSeqJournalFolder": "/Users/andrew.shell/code/myLogseqBlog-main/graph/journals/",
    "opmlJournalFile": "/Users/andrew.shell/code/myLogseqBlog-main/graph/journal.opml",
    "blogTitle": "Andrew's LogSeq Blog",
    "blogDescription": "Connecting LogSeq for writing with Drummer for publishing.",
    "blogWhenCreated": "Wed, 13 Jan 2022 17:36:18 GMT",
    "blogTimeZoneOffset": -6,
    "blogCopyright": "Copyright 2022, Andrew Shell.",
    "blogUrlHeaderImage": "http://scripting.com/images/2021/07/07/hopperGasStation.png",
    "blogUseCache": false,
    "urlTwitterServer": "http://drummer.scripting.com/",
    "oauth_token": "xxx",
    "oauth_token_secret": "xxx"
}
addJournalFileToOutline: fname == 2022_01_13.md, mdtext.length == 201
logseqpublish: opmltext.length == 1535
drummerCms: err.message == Can't read the file because there was an error. Code == 500.
```

* The local file journal.opml was generated correctly
* The file blog.opml is present in drummer
* Going to http://drummercms.scripting.com/build?blog=andrewshell in a browser returns the following error:

```
{
    "message": "Can't build the blog for \"andrewshell\" because blog.opml doesn't exist in Drummer, or is private."
}
```

* Looks like blog.opml is private

**Comment by scripting** [comment]
Thanks @andrewshell — I left out a step.

**Comment by scripting** [comment]
@andrewshell -- the long version of the story is that when I did this with my blog I did it manually, and forgot that step when I wrote the docs. i just looked at the code, and the change is obvious, but not something i can do right now (not enough time), so the fix for now is to open blog.opml in drummer and chose the Make Outline Public command from the File menu. I will put this fix in the docs so people who try it now will have success. However it will be possible to bake this into the app so it isnt even a step.

**Comment by andrewshell** [comment]
It's working now:
http://oldschool.scripting.com/andrewshell/

**Comment by scripting** [comment]
Here's the update to the docs.

https://github.com/scripting/myLogseqBlog#one-more-step-make-blogopml-public

**Comment by scripting** [comment]
BTW it would be helpful if you post your notes in the [initial thread](https://github.com/scripting/myLogseqBlog/issues/1), that's the link I'm advertising, the idea is to help each other as the test proceeds. 

https://github.com/scripting/myLogseqBlog/issues/1
